version: '3'

services:
  app:
    image: nextjs-dev
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./src/pages:/app/src/pages
      - ./public:/app/public
      - ./src/styles:/app/src/styles