// Index route
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Image from 'next/image';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next Apps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Link href="/ticket">
          <a>
            <Image src="/book.jpg" width="500" height="300" alt="go to APP" title="go to APP" />
          </a>
        </Link>
      </main>
    </div>
  );
}
